version: "3.9"

services:
    client:
        image: godfish_test/postgres/client:latest
        container_name: godfish_ci_postgres_client
        depends_on:
          - server
        entrypoint: /client.sh server
        env_file:
            - env
        environment:
            CGO_ENABLED: 0
            DB_DSN: "postgresql://godfish:password@server:5432/godfish_test?sslmode=disable"
        tty: true
    server:
        image: godfish_test/postgres/server:latest
        container_name: godfish_ci_postgres_server
        env_file:
            - env
        expose:
            - 5432
        volumes:
            -
              type: volume
              source: server
              target: /var/lib/postgresql/data

volumes:
    server:
