version: "3.9"

services:
    client:
        build:
            context: ../..
            dockerfile: .ci/postgres/client.Dockerfile
        depends_on:
          - server
        entrypoint: /client.sh server
        env_file:
            - env
        environment:
            CGO_ENABLED: 0
            DB_DSN: "postgresql://godfish:password@server:5432/godfish_test?sslmode=disable"
        tty: true
    server:
        build:
            context: ../..
            dockerfile: .ci/postgres/server_v14.Dockerfile
        env_file:
            - env
        expose:
            - 5432
        volumes:
            -
              type: volume
              source: server
              target: /var/lib/postgresql/data

volumes:
    server:
