services:
    client:
        build:
            context: ../..
            dockerfile: .ci/postgres/client.Containerfile
        depends_on:
            - server
        entrypoint: /client.sh server
        env_file:
            - env
        environment:
            CGO_ENABLED: 0
            DB_DSN: "postgresql://godfish:password@server:5432/godfish_test?sslmode=disable"
        tty: true
        volumes:
            -
                type: bind
                source: /tmp/godfish_test/postgres_v15/.test_coverage
                target: /tmp
    server:
        build:
            context: ../..
            dockerfile: .ci/postgres/server_v15.Containerfile
        env_file:
            - env
        expose:
            - 5432
        volumes:
            -
                type: volume
                source: server
                target: /var/lib/postgresql/data

volumes:
    server:
