coverage:
  status:
    project: 'off'
    patch: 'off'

ignore:
  # This package tests implementations of Driver. Shouldn't be counted in coverage.
  - ./internal/test

parsers:
  go:
    # Codecov has the concept of partial hits, which have a lower code coverage
    # value than a full hit. This option deactivates partial hits so the
    # coverage percentage is closer to what you may get with native golang
    # tooling, like the -coverprofile flag.
    partials_as_hits: true
