// Package godfish is a database migration library.
// It's built to serve the command line tool, but could be used for more
// customized situations, such as embedding migrations into a binary.
package godfish

import (
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/rafaelespinoza/godfish/internal"
)

const msgPrefix = "godfish"

// CreateMigrationFilesWith takes care of setting up a new DB migration by
// generating empty migration files in a directory at dirpath. Passing in true
// for reversible means that a complementary file will be made for rollbacks.
//
// # Filenames
//
// By default, a migration file's basename would be
//
//	${direction}-${version}-${name}.sql
//
// Valid directions are:
//
//   - forward, migrate, up
//   - reverse, rollback, down
//
// The version is autogenerated. Filenames created with this tool will be a UTC
// timestamp of the creation. The form is YYYYMMDDHHmmss.
//
// # Relevant opts
//
//   - [WithForwardLabel]. If passed in with a non-zero value, then it will set
//     the "direction" part of the filename for regular, forward migrations.
//     At this time, valid values are "forward", "migrate", "up".
//     When passed in with any other value, then an error is returned.
//     When this option is omitted, then the direction label will be the default,
//     which is "forward".
//   - [WithReverseLabel]. If passed in with a non-zero value, then it will set
//     the "direction" part of the filename the reverse migration; in other
//     words, the complementary rollback migration.
//     At this time, valid values are "reverse", "rollback", "down".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then the direction label will be the default,
//     which is "reverse".
//   - [WithFilenameExtension]. If passed in with a non-zero value, then it will set
//     the filename extension.
//     When this option is omitted, then this function will use the default,
//     which is ".sql".
func CreateMigrationFilesWith(migrationName string, reversible bool, dirpath string, opts ...Opter) (err error) {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "CreateMigrationFilesWith", err)
	}

	return createMigrationFiles(migrationName, reversible, dirpath, o.forwardLabel, o.reverseLabel, o.filenameExt)
}

// CreateMigrationFiles takes care of setting up a new DB migration by
// generating empty migration files in a directory at dirpath. Passing in true
// for reversible means that a complementary file will be made for rollbacks.
// Names for directions in the filename could be overridden from their default
// values (forward and reverse) with the input vars fwdlabel, revlabel when
// non-empty.
//
// Deprecated: This function will be removed in a future release.
// New code should use [CreateMigrationFilesWith].
// Current code is encouraged to adjust as well.
func CreateMigrationFiles(migrationName string, reversible bool, dirpath, fwdlabel, revlabel string) (err error) {
	return createMigrationFiles(migrationName, reversible, dirpath, fwdlabel, revlabel, ".sql")
}

func createMigrationFiles(migrationName string, reversible bool, dirpath, fwdlabel, revlabel, ext string) error {
	ext = cmp.Or(ext, ".sql")

	params, err := internal.NewMigrationParams(migrationName, reversible, dirpath, fwdlabel, revlabel, ext)
	if err != nil {
		return err
	}

	return params.GenerateFiles()
}

// MigrateWith applies one or more available migrations in the forward direction.
//
// # Relevant opts
//
//   - [WithTargetVersion]. If passed in with a non-zero value, then this
//     function will apply up to and including the target migration.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will apply all available
//     migrations.
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func MigrateWith(ctx context.Context, driver Driver, dirFS fs.FS, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "MigrateWith", err)
	}

	return migrate(ctx, driver, dirFS, true, o.targetVersion, o.migrationsTable)
}

// RollbackWith applies one or more available migrations in the reverse direction.
//
// # Relevant opts
//
//   - [WithTargetVersion]. If passed in with a non-zero value, then this
//     function will rollback down to and including the target migration.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will apply all
//     available rollback migrations.
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func RollbackWith(ctx context.Context, driver Driver, dirFS fs.FS, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "RollbackWith", err)
	}

	return migrate(ctx, driver, dirFS, false, o.targetVersion, o.migrationsTable)
}

// Migrate executes all migrations at the directory dirFS in the specified
// direction. When forward is true, it will seek migrations with a forward
// direction and apply them up to and including the one with a version matching
// finishAtVersion. Likewise, when forward is false, then it seeks migrations
// with a reverse direction and runs them.
//
// The migrationsTable input sets the DB table for storing the current DB
// migration state. If empty, then it's set to a default value of
// "schema_migrations". The named DB table will be automatically created unless
// it already exists.
//
// Deprecated: This function will be removed in a future release.
// New code should use [MigrateWith] or [RollbackWith], depending the direction
// of the migration(s) to apply.
// Current code is encouraged to adjust as well.
func Migrate(ctx context.Context, driver Driver, dirFS fs.FS, forward bool, finishAtVersion string, migrationsTable string) (err error) {
	return migrate(ctx, driver, dirFS, forward, finishAtVersion, migrationsTable)
}

func migrate(ctx context.Context, driver Driver, dirFS fs.FS, forward bool, finishAtVersion string, migrationsTable string) (err error) {
	migrationsTable = cmp.Or(migrationsTable, internal.DefaultMigrationsTableName)
	var migrations []*internal.Migration
	direction := internal.DirReverse
	if forward {
		direction = internal.DirForward
	}

	if finishAtVersion == "" && direction == internal.DirForward {
		finishAtVersion = internal.MaxVersion
	} else if finishAtVersion == "" && direction == internal.DirReverse {
		finishAtVersion = internal.MinVersion
	}

	finder := migrationFinder{
		direction:       direction,
		dirFS:           dirFS,
		finishAtVersion: finishAtVersion,
	}
	if migrations, err = finder.query(ctx, driver, migrationsTable); err != nil {
		return
	}

	// Before executing any migrations, ensure there is a known file for each one.
	for _, mig := range migrations {
		if mig.Filename == "" {
			return fmt.Errorf(
				"migration with direction (%q) version (%q) label (%q) does not seem to have a Filename",
				mig.Indirection.Label, mig.Version.String(), mig.Label,
			)
		}
	}

	for _, mig := range migrations {
		if err = runMigration(ctx, driver, dirFS, mig, migrationsTable); err != nil {
			return
		}
	}
	return
}

// ErrSchemaMigrationsDoesNotExist means there is no database table to
// record migration status.
var ErrSchemaMigrationsDoesNotExist = errors.New("schema migrations table does not exist")

// ApplyMigrationWith runs one forward migration at the directory dirFS with
// the specified version.
// This function could be used for cherry-picking one forward migration to
// apply, even if the targeted migration is not the next available one. It will
// not attempt to run migrations in between the current version and the target
// version.
//
// # Relevant opts
//
//   - [WithTargetVersion]. If passed in with a non-zero value, then this
//     function will seek the targeted migration in the forward direction and
//     apply it. The targeted version may be any greater than the current.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will apply the closest
//     available forward migration.
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func ApplyMigrationWith(ctx context.Context, driver Driver, dirFS fs.FS, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "ApplyMigrationWith", err)
	}

	return applyMigration(ctx, driver, dirFS, true, o.targetVersion, o.migrationsTable)
}

// ApplyRollbackWith runs one rollback migration at the directory dirFS with
// the specified version.
// This function could be used for cherry-picking one rollback migration to
// apply, even if the targeted rollback is not the closest available one. It
// will not attempt to run migrations in between the current and the target
// version.
//
// # Relevant opts
//
//   - [WithTargetVersion]. If passed in with a non-zero value, then this
//     function will seek the targeted migration in the reverse direction and
//     apply it. The targeted version may be any less than the current.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will apply the closest
//     available rollback migration.
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func ApplyRollbackWith(ctx context.Context, driver Driver, dirFS fs.FS, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "ApplyRollbackWith", err)
	}

	return applyMigration(ctx, driver, dirFS, false, o.targetVersion, o.migrationsTable)
}

// ApplyMigration runs a migration at the directory dirFS with the specified
// version and direction. When forward is true, it will target a migration with
// a forward direction. Likewise when forward is false, then it targets a
// migration with a reverse direction.
//
// The migrationsTable input sets the DB table for storing the current DB
// migration state. If empty, then it's set to a default value of
// "schema_migrations". The named DB table will be automatically created unless
// it already exists.
//
// Deprecated: This function will be removed in a future release.
// New code should use [ApplyMigrationWith] or [ApplyRollbackWith], depending
// the direction of the migration to apply.
// Current code is encouraged to adjust as well.
func ApplyMigration(ctx context.Context, driver Driver, dirFS fs.FS, forward bool, version, migrationsTable string) (err error) {
	return applyMigration(ctx, driver, dirFS, forward, version, migrationsTable)
}

func applyMigration(ctx context.Context, driver Driver, dirFS fs.FS, forward bool, version, migrationsTable string) error {
	migrationsTable = cmp.Or(migrationsTable, internal.DefaultMigrationsTableName)

	direction := internal.DirReverse
	if forward {
		direction = internal.DirForward
	}

	var mig *internal.Migration
	if version != "" {
		var err error
		if mig, err = findParseMigration(dirFS, direction, version); err != nil {
			return fmt.Errorf("trying to find, parse migration to apply: %w", err)
		}
	} else {
		// attempt to find the next version to apply in the direction
		var limit string
		if direction == internal.DirForward {
			limit = internal.MaxVersion
		}
		finder := migrationFinder{
			direction:       direction,
			dirFS:           dirFS,
			finishAtVersion: limit,
		}
		toApply, ierr := finder.query(ctx, driver, migrationsTable)
		if ierr != nil {
			return fmt.Errorf("specified no version; error attempting to find one; %w", ierr)
		}
		if len(toApply) < 1 {
			return fmt.Errorf("version %w", internal.ErrNotFound)
		}
		// There may be more than 1 migration that could be applied. However, we're
		// only interested in the nearest migration in the said direction.
		mig = toApply[0]
	}

	if mig == nil {
		return fmt.Errorf("trying to apply migration, but it's empty, forward=%t version=%s", forward, version)
	}

	if err := runMigration(ctx, driver, dirFS, mig, migrationsTable); err != nil {
		return fmt.Errorf("running migration with filename %q: %w", mig.Filename, err)
	}
	return nil
}

// runMigration executes a migration against the database. The input, pathToFile
// should be relative to the current working directory.
func runMigration(ctx context.Context, driver Driver, dir fs.FS, mig *internal.Migration, migrationsTable string) (err error) {
	if mig.Filename == "" {
		return fmt.Errorf(
			"migration (direction=%q, version=%s, label=%s) was not assigned a filename",
			mig.Indirection.Label, mig.Version.String(), mig.Label,
		)
	}
	var data []byte
	if data, err = fs.ReadFile(dir, filepath.Clean(mig.Filename)); err != nil {
		err = fmt.Errorf("%s: reading file in prep for running migration: %w", msgPrefix, err)
		return
	}
	gerund := "migrating"
	if mig.Indirection.Value == internal.DirReverse {
		gerund = "rolling back"
	}

	lgr := slog.With(slog.String("path_to_file", mig.Filename), slog.String("version", mig.Version.String()))
	lgr.Info(gerund + " ...")
	startTime := time.Now()

	if err = driver.Execute(ctx, string(data)); err != nil {
		err = fmt.Errorf("%w; path_to_file: %s; %w", internal.ErrExecutingMigration, mig.Filename, err)
		lgr.Error("executing migration", slog.Any("error", err), makeDurationMSAttr(startTime))
		return
	}
	if err = driver.CreateSchemaMigrationsTable(ctx, migrationsTable); err != nil {
		lgr.Error("creating schema migrations table", slog.Any("error", err), makeDurationMSAttr(startTime))
		return
	}
	err = driver.UpdateSchemaMigrations(
		ctx,
		migrationsTable,
		mig.Indirection.Value == internal.DirForward,
		mig.Version.String(),
		mig.Label,
	)
	if err != nil {
		lgr.Error("updating schema migrations table", slog.Any("error", err), makeDurationMSAttr(startTime))
	} else {
		lgr.Info("ok", makeDurationMSAttr(startTime))
	}
	return
}

// makeDurationMSAttr calculates how much time, in milliseconds, has transpired
// since startedAt and returns a slog.KindInt64 attr with the key duration_ms.
func makeDurationMSAttr(startedAt time.Time) slog.Attr {
	dur := time.Since(startedAt)
	return slog.Int64("duration_ms", dur.Milliseconds())
}

// InfoWith outputs migration status.
//
// # Example of tsv format
//
// (seems to look better in a terminal emulator)
//
//	i	version	applied	executed_at		label	filename
//	0	1234	true	2026-06-21 15:04:05	alpha	forward-1234-alpha.sql
//	1	2345	true	2026-07-01 03:40:50	bravo	forward-2345-bravo.sql
//	2	3456	false	-			charlie	forward-3456-charlie.sql
//
// # Example of json format
//
//	{"i":0,"version":"1234","applied":true,"executed_at":"2026-06-21 15:04:05","label":"alpha","filename":"forward-1234-alpha.sql"}
//	{"i":1,"version":"2345","applied":true,"executed_at":"2026-07-01 03:40:50","label":"bravo","filename":"forward-2345-bravo.sql"}
//	{"i":2,"version":"3456","applied":false,"executed_at":"","label":"charlie","filename":"forward-3456-charlie.sql"}
//
// # Relevant opts
//   - [WithWriter]. If passed in with a non-zero value, then it will set the
//     output writer.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then it will write to standard output.
//   - [WithFormat]. If passed in with a non-zero value, then it will set the
//     output format. Supported formats at this time are JSON, TSV.
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted then it will write in TSV format.
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func InfoWith(ctx context.Context, driver Driver, directory fs.FS, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "InfoWith", err)
	}
	return info(ctx, driver, directory, true, "", o.writer, o.format, o.migrationsTable)
}

// Info writes status of migrations to w in formats json or tsv.
//
// The migrationsTable input sets the DB table for storing the current DB
// migration state. If empty, then it's set to a default value of
// "schema_migrations". Unlike other functions that use the DB table to check
// the migration state, this function does not create a new table, nor does it
// have the need to.
//
// Deprecated: This function will be removed in a future release.
// New code should use [InfoWith].
// Current code is encouraged to adjust as well.
func Info(ctx context.Context, driver Driver, directory fs.FS, forward bool, finishAtVersion string, w io.Writer, format string, migrationsTable string) (err error) {
	return info(ctx, driver, directory, forward, finishAtVersion, w, format, migrationsTable)
}

func info(ctx context.Context, driver Driver, directory fs.FS, forward bool, finishAtVersion string, w io.Writer, format string, migrationsTable string) (err error) {
	w = cmp.Or[io.Writer](w, os.Stdout)
	format = cmp.Or(format, "tsv")
	migrationsTable = cmp.Or(migrationsTable, internal.DefaultMigrationsTableName)

	direction := internal.DirReverse
	if forward {
		direction = internal.DirForward
	}

	finder := migrationFinder{
		direction:       direction,
		dirFS:           directory,
		finishAtVersion: finishAtVersion,
		infoPrinter:     choosePrinter(format, w),
	}
	_, err = finder.query(ctx, driver, migrationsTable)
	return
}

func choosePrinter(format string, w io.Writer) (out internal.InfoPrinter) {
	if format == "json" {
		out = internal.NewJSON(w)
		return
	}

	if format != "tsv" && format != "" {
		slog.Warn("unknown format, defaulting to tsv", slog.String("format", format))
	}
	out = internal.NewTSV(w)
	return
}

// Init creates a configuration file at pathToFile unless it already exists.
func Init(pathToFile string) (err error) {
	_, err = os.Stat(pathToFile)
	if err == nil {
		slog.Info("config file already present", slog.String("path_to_file", pathToFile))
		return nil
	}
	if !os.IsNotExist(err) {
		return err
	}

	var data []byte
	if data, err = json.MarshalIndent(internal.Config{}, "", "\t"); err != nil {
		return err
	}
	return os.WriteFile(
		pathToFile,
		append(data, byte('\n')),
		os.FileMode(0644),
	)
}

func findParseMigration(fsys fs.FS, direction internal.Direction, version string) (*internal.Migration, error) {
	basename, err := findUniqueByPrefix(fsys, direction, version)
	if err != nil {
		return nil, fmt.Errorf("attempting to find migration file by prefix: %w", err)
	}
	basename = filepath.Clean(basename)
	mig, err := internal.ParseMigration(internal.Filename(basename))
	if err != nil {
		return nil, fmt.Errorf("parsing migration metadata with filename %q: %w", basename, err)
	}
	mig.Filename = basename
	return mig, nil
}

// findUniqueByPrefix returns the relative path of the single file matching prefix.
// It errors early if 0 or > 1 matches are found.
func findUniqueByPrefix(fsys fs.FS, direction internal.Direction, version string) (string, error) {
	entries, err := fs.ReadDir(fsys, ".")
	if err != nil {
		return "", fmt.Errorf("reading directory entries: %w", err)
	}

	var match string
	var found bool
	var directionNames []string
	switch direction {
	case internal.DirForward:
		directionNames = internal.ForwardDirections
	case internal.DirReverse:
		directionNames = internal.ReverseDirections
	}

	for _, entry := range entries {
		basename := entry.Name()
		if entry.IsDir() {
			slog.Info("searching for available migrations and found directory, skipping", slog.String("path", basename))
			continue
		}

		for _, alias := range directionNames {
			filenamePrefix := alias + "-" + version
			if strings.HasPrefix(basename, filenamePrefix) {
				if found {
					return "", fmt.Errorf(
						"%s: too many migration files with matching direction-version, %q",
						msgPrefix, filenamePrefix,
					)
				}
				match = basename
				found = true
			}
		}
	}

	if !found {
		return "", fmt.Errorf("version %w", internal.ErrNotFound)
	}

	return filepath.Clean(match), nil
}

// migrationFinder is a collection of named parameters to use when searching
// for migrations to apply.
type migrationFinder struct {
	direction       internal.Direction
	dirFS           fs.FS
	finishAtVersion string
	infoPrinter     internal.InfoPrinter
}

// query returns a list of Migrations to apply.
func (m *migrationFinder) query(ctx context.Context, driver Driver, migrationsTable string) (out []*internal.Migration, err error) {
	lgr := slog.With(slog.String("func", "(*migrationFinder).query"))

	availableByVersion, orderedAvailableVersions, err := m.available()
	if err != nil {
		return nil, fmt.Errorf("getting available migrations: %w", err)
	}
	available := make([]*internal.Migration, len(orderedAvailableVersions))
	for i, version := range orderedAvailableVersions {
		available[i] = availableByVersion[version]
	}
	lgr.Debug("found available migrations",
		slog.Int("count", len(availableByVersion)),
		slog.Any("available", internal.Migrations(available)),
	)

	applied, err := scanAppliedVersions(ctx, driver, migrationsTable, availableByVersion)
	if errors.Is(err, ErrSchemaMigrationsDoesNotExist) {
		// The next invocation of CreateSchemaMigrationsTable should fix this.
		// We can continue with zero value for now.
		slog.Info(
			"no migrations applied yet, continuing...",
			slog.Any("message", err), slog.String("migrations_table", migrationsTable),
		)
	} else if err != nil {
		return
	}
	lgr.Debug("scanned applied migrations",
		slog.Int("count", len(applied)),
		slog.Any("applied", internal.Migrations(applied)),
	)

	defer func() {
		if m.infoPrinter == nil {
			return
		}

		if perr := printMigrations(m.infoPrinter, applied, out); perr != nil {
			slog.Error("printing migrations", slog.Any("error", perr))
		}
	}()

	lgr.Debug("about to filter migrations", slog.Group("migration_finder",
		slog.String("direction", m.direction.String()),
		slog.String("finish_at_version", m.finishAtVersion),
	))

	toApply, err := m.filter(applied, available)
	if err != nil {
		return
	}
	lgr.Debug("filtered migrations toApply", slog.Group("to_apply",
		slog.Int("count", len(toApply)),
		slog.Any("vals", internal.Migrations(toApply)),
	))

	var useDefaultRollbackVersion bool
	if m.finishAtVersion == "" && m.direction == internal.DirForward {
		m.finishAtVersion = internal.MaxVersion
	} else if m.finishAtVersion == "" && m.direction == internal.DirReverse {
		if len(toApply) == 0 {
			return
		}
		useDefaultRollbackVersion = true
		m.finishAtVersion = toApply[0].Version.String()
	}
	var finish internal.Version
	if finish, err = internal.ParseVersion(m.finishAtVersion); err != nil {
		return
	}
	lgr.Debug("about to collect migrations to apply in a loop",
		slog.String("finish_at_version", finish.String()),
		slog.String("direction", m.direction.String()),
		slog.Bool("use_default_rollback_version", useDefaultRollbackVersion),
		slog.Int("num_to_apply", len(toApply)),
	)

	for i, mig := range toApply {
		version := mig.Version
		lgr.Debug("considering migration to apply", slog.Int("i", i), slog.String("version", version.String()))
		if m.direction == internal.DirForward && finish.Before(version) {
			break
		}
		if m.direction == internal.DirReverse {
			if version.Before(finish) {
				break
			}
			if !useDefaultRollbackVersion && version.Before(finish) {
				break
			}
		}
		lgr.Debug("collected migration to apply", slog.Int("i", i), slog.String("version", version.String()))
		out = append(out, mig)
	}
	return
}

// available loads Migrations in the m.dirFS with a direction matching
// m.direction. It returns them in a map where the key is the migration
// version and value is the *Migration, an ordered slice of migration versions.
// and if non-empty, an error. Entries in the fs.FS that are files, and have
// a basename in a form: "${direction}-${version}-${label}", are parsed into
// migration values. The migration file's basename is also added here.
func (m *migrationFinder) available() (map[int64]*internal.Migration, []int64, error) {
	dirEntries, err := fs.ReadDir(m.dirFS, ".")
	if err != nil {
		return nil, nil, fmt.Errorf("reading directory entries: %w", err)
	}
	if m.direction != internal.DirForward {
		slices.Reverse(dirEntries)
	}

	migrations := make(map[int64]*internal.Migration, len(dirEntries))
	orderedVersions := make([]int64, 0, len(dirEntries))

	for _, dirEntry := range dirEntries {
		name := dirEntry.Name()
		if dirEntry.IsDir() {
			slog.Info("searching for available migrations and found directory, skipping", slog.String("path", name))
			continue
		}

		mig, ierr := internal.ParseMigration(internal.Filename(name))
		if errors.Is(ierr, internal.ErrDataInvalid) {
			slog.Warn("parsing migration filename, skipping over this one", slog.String("filename", name), slog.String("error", ierr.Error()))
			continue
		} else if ierr != nil {
			return nil, nil, ierr
		}
		dir := mig.Indirection.Value
		if dir != m.direction {
			continue
		}
		mig.Filename = name
		version := mig.Version.Value()
		migrations[version] = mig
		orderedVersions = append(orderedVersions, version)
	}

	return migrations, slices.Clip(orderedVersions), nil
}

// scanAppliedVersions reads the DB for info on already-applied migrations.
// A side effect of this operation is a signal of whether or not the
// migrationsTable needs to be "upgraded". That is, if the driver detects
// that the table is missing certain columns, and the driver is properly
// implemented as described by the [Driver.AppliedVersions] method, then this
// function will return an error, [ErrSchemaMigrationsMissingColumns].
//
// The map, availableByVersion, may be used to enrich more metadata about the
// migration that may not be in the database. One use case for this is when
// reading the migrationsTable with data inserted prior to v0.14.0 of this
// library. ie: the `label` is empty, so try to derive it from another source.
//
// This enhancement will be only attempted if the map is non-nil.
// When seeking migrations to apply, you'll definitely want to pass this in,
// because it's a good way to set the migration's Filename field, which is
// pretty important when you want to read the file later.
// But if you only you want to check if the DB table needs to be upgraded, then
// it's ok to pass an empty map.
func scanAppliedVersions(ctx context.Context, driver Driver, migrationsTable string, availableByVersion map[int64]*internal.Migration) (out []*internal.Migration, err error) {
	var rows AppliedVersions
	if rows, err = driver.AppliedVersions(ctx, migrationsTable); err != nil {
		return
	}
	defer func() {
		if cerr := rows.Close(); cerr != nil {
			slog.Warn("closing rows from func scanAppliedVersions", slog.Any("error", cerr))
		}
	}()
	for rows.Next() {
		var version, label string
		var executedAt int64
		if err = rows.Scan(&version, &label, &executedAt); err != nil {
			return
		}

		ver, verr := internal.ParseVersion(version)
		if verr != nil {
			err = fmt.Errorf("%w; while scanning applied versions, parsing version (%v) from DB: %w", internal.ErrDataInvalid, version, verr)
			return
		}
		var executedAtTime time.Time
		if executedAt > 0 {
			executedAtTime = time.Unix(executedAt, 0).UTC()
		}
		mig := internal.Migration{
			Indirection: internal.Indirection{Value: internal.DirForward},
			Label:       label,
			Version:     ver,
			ExecutedAt:  executedAtTime,
			Applied:     true,
		}

		if availableByVersion != nil {
			if knownAvailableMigration, found := availableByVersion[ver.Value()]; found {
				mig.Filename = knownAvailableMigration.Filename
				// If this data was originally inserted before the label column was present,
				// then it would be empty in the DB. Attempt to reconstruct the Label field
				// based on a matching filename.
				if mig.Label == "" {
					mig.Label = knownAvailableMigration.Label
				}
			}
		}

		out = append(out, &mig)
	}

	return
}

// filter compares lists of applied and available migrations, then selects a
// list of migrations to apply.
func (m *migrationFinder) filter(applied, available []*internal.Migration) (out []*internal.Migration, err error) {
	allVersions := make(map[int64]*internal.Migration)
	uniqueToApplied := make(map[int64]*internal.Migration)
	for _, mig := range applied {
		version := mig.Version.Value()
		uniqueToApplied[version] = mig
		allVersions[version] = mig
	}
	uniqueToAvailable := make(map[int64]*internal.Migration)
	for _, mig := range available {
		version := mig.Version.Value()
		if _, ok := uniqueToApplied[version]; ok {
			delete(uniqueToApplied, version)
		} else {
			uniqueToAvailable[version] = mig
			allVersions[version] = mig
		}
	}

	if m.direction == internal.DirForward {
		for version, mig := range allVersions {
			_, isApplied := uniqueToApplied[version]
			_, isAvailable := uniqueToAvailable[version]
			if !isApplied && isAvailable {
				out = append(out, mig)
			}
		}
	} else {
		for version, mig := range allVersions {
			_, appliedOK := uniqueToApplied[version]
			_, availableOK := uniqueToAvailable[version]
			if !appliedOK && !availableOK {
				// The Migration direction is artificially set to Forward from a
				// previous step. Here, we correct it. Also, we're guessing what
				// the original filename was, by assuming that the list of
				// forward directions is in the same order as the corresponding
				// reverse directions. It's kind of hacky, I know.
				var mut *internal.Migration
				indirection := internal.Indirection{
					Value: internal.DirReverse,
					Label: "reverse", // need to have something here, it gets restored later.
				}
				mut, err = newMigration(mig.Version.String(), indirection, mig.Label)
				if err != nil {
					return
				}
				for i, fwd := range internal.ForwardDirections {
					// Restore the direction label for reverse migration based
					// on corresponding label for the known forward migration.
					//
					// Another assumption, the filename format will never
					// change. If it does change, for example: it is
					// "${version}-${direction}-${label}", instead of
					// "${direction}-${version}-${label}", then this won't work.
					if mig.Indirection.Label == fwd {
						indirection.Label = internal.ReverseDirections[i]
						mut, err = newMigration(mig.Version.String(), indirection, mig.Label)
						if err != nil {
							return
						}
						break
					}
				}
				if mut.Label == "" {
					err = fmt.Errorf(
						"direction.Label empty; direction.Value: %q, version: %v, label: %q",
						mut.Indirection, mut.Version.String(), mut.Label,
					)
					return
				}
				mut.Filename = mig.Filename
				out = append(out, mut)
			}
		}
	}
	if m.direction == internal.DirForward {
		sort.Slice(out, func(i, j int) bool {
			return out[i].Version.Before(out[j].Version)
		})
	} else {
		sort.Slice(out, func(i, j int) bool {
			return out[j].Version.Before(out[i].Version)
		})
	}
	return
}

func newMigration(version string, ind internal.Indirection, label string) (out *internal.Migration, err error) {
	fn := internal.MakeFilename(version, ind, label)
	out, err = internal.ParseMigration(fn)
	return
}

func printMigrations(p internal.InfoPrinter, applied, toApply []*internal.Migration) error {
	toPrint := make([]*internal.Migration, 0, len(applied)+len(toApply))
	toPrint = append(toPrint, applied...)
	toPrint = append(toPrint, toApply...)
	return p.PrintInfo(toPrint)
}

// ErrSchemaMigrationsMissingColumns means the schema migrations table exists,
// but is missing some extra metadata columns.
var ErrSchemaMigrationsMissingColumns = errors.New("schema migrations table is missing columns")

// UpgradeSchemaMigrationsWith may alter an existing schema migrations table, to
// have newer metadata columns. If the table was created with v0.14.0 or lower,
// then it likely could be upgraded. If the driver detects that the columns
// already exist in the designated migrations table, then the upgrade is avoided
// without error.
//
// # Relevant opts
//
//   - [WithMigrationsTable]. If passed in with a non-zero value, then this
//     function will override the default value of "schema_migrations".
//     When passed in with a zero value, then an error is returned.
//     When this option is omitted, then this function will use the default.
//     This DB table will be automatically created unless it already exists.
func UpgradeSchemaMigrationsWith(ctx context.Context, driver Driver, opts ...Opter) error {
	o, err := setOptions(opts...)
	if err != nil {
		return fmt.Errorf("%s.%s: %w", msgPrefix, "UpgradeSchemaMigrationsWith", err)
	}
	return UpgradeSchemaMigrations(ctx, driver, o.migrationsTable)
}

// UpgradeSchemaMigrations may alter an existing schema migrations table,
// migrationsTable, to have newer metadata columns. If the table was created
// with v0.14.0 or lower, then it likely could be upgraded. If the driver
// detects that the columns already exist in migrationsTable, then the upgrade
// is avoided without error. If migrationsTable is empty, then it's set to a
// default value of "schema_migrations".
//
// Deprecated: This function will be removed in a future release.
// New code should use [UpgradeSchemaMigrationsWith].
// Current code is encouraged to adjust as well.
func UpgradeSchemaMigrations(ctx context.Context, driver Driver, migrationsTable string) (err error) {
	return upgradeSchemaMigrations(ctx, driver, migrationsTable)
}

func upgradeSchemaMigrations(ctx context.Context, driver Driver, migrationsTable string) (err error) {
	migrationsTable = cmp.Or(migrationsTable, internal.DefaultMigrationsTableName)

	lgr := slog.With(slog.String("migrations_table", migrationsTable))

	// Check if table exists but needs an upgrade
	//
	// Keep the map empty here b/c we're not actually interested in the contents
	// at this time. We want to test if the DB table can be read at all w/o error.
	var dummyMigrationMap map[int64]*internal.Migration
	if _, err = scanAppliedVersions(ctx, driver, migrationsTable, dummyMigrationMap); err != nil {
		lgr.Debug("from UpgradeSchemaMigrations", slog.Any("error", err))
		if errors.Is(err, ErrSchemaMigrationsDoesNotExist) {
			err = fmt.Errorf("%w; cannot upgrade if it does not exist yet", err)
			return
		} else if !errors.Is(err, ErrSchemaMigrationsMissingColumns) {
			return
		}

		err = nil // Table exists but is missing columns
	} else {
		lgr.Info("schema migrations table appears to be in expected shape, no need to upgrade")
		return
	}

	startTime := time.Now()
	lgr.Info("upgrading schema migrations table...")
	if err = driver.UpgradeSchemaMigrations(ctx, migrationsTable); err != nil {
		lgr.Error("failed to upgrade schema migrations table", slog.Any("error", err), makeDurationMSAttr(startTime))
		return err
	}
	lgr.Info("schema migrations table upgrade complete", makeDurationMSAttr(startTime))
	return nil
}
