services:
    client:
        build:
            context: ../..
            dockerfile: .ci/sqlserver/client.Containerfile
        depends_on:
          - server
        entrypoint: /client.sh
        env_file:
            - env
        environment:
            CGO_ENABLED: 0
        volumes:
          -
            type: bind
            source: ../../.ci/.test_coverage/sqlserver
            target: /tmp/test_coverage
    server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env_file:
            - env
        environment:
            ACCEPT_EULA: '1'
