version: "3.9"

services:
    client:
        build:
            context: ../..
            dockerfile: .ci/sqlserver/client.Dockerfile
        depends_on:
          - server
        entrypoint: /client.sh
        env_file:
            - env
        environment:
            CGO_ENABLED: 0
        tty: true
    server:
        image: mcr.microsoft.com/mssql/server:latest
        env_file:
            - env
        environment:
            ACCEPT_EULA: '1'
