services:
    client:
        build:
            context: ../..
            dockerfile: .ci/cassandra/client.Containerfile
        depends_on:
            - server
        entrypoint: /client.sh server
        environment:
            CGO_ENABLED: 0
            DB_DSN: "cassandra://server:9042/godfish_test?timeout_ms=2000&connect_timeout_ms=2000"
        tty: true
    server:
        image: docker.io/cassandra:3.11.12
        expose:
            - "9042"
        volumes:
            -
              type: volume
              source: server
              target: /var/lib/cassandra
volumes:
    server:
