services:
    client:
        build:
            context: ../..
            dockerfile: .ci/cassandra/client.Containerfile
        depends_on:
            - server
        entrypoint: /client.sh server
        environment:
            CGO_ENABLED: 0
            # The default timeouts are 11s, but want to be explicit here.
            DB_DSN: "cassandra://server:9042/godfish_test?timeout_ms=11000&connect_timeout_ms=11000"
            GITHUB_TOKEN: # Mitigate rate limits.
        volumes:
            -
                type: bind
                source: ../../.ci/.test_coverage/cassandra_v5
                target: /tmp/test_coverage
    server:
        image: docker.io/cassandra:5.0.6
        expose:
            - "9042"
        volumes:
            -
                type: volume
                source: server
                target: /var/lib/cassandra
volumes:
    server:
