#!/usr/bin/env sh

usage() {
	_usage_message="Usage: $(basename "${0}") <driver> [...arguments]

Description:
	This script is a unified entrypoint for the DB migration manager, godfish.
	Each DB driver binary is compiled to be independently of other DB drivers,
	rather than bundling them all into a large monolithic executable.

	To mitigate cluttering of your PATH, these driver-specific binaries may
	be moved elsewhere (such as a libexec/ dir). This script takes the driver
	name, and then routes the remaining arguments to the corresponding binary.

	The upstream repository is:
		https://github.com/rafaelespinoza/godfish
	The Homebrew tap lives at:
		https://github.com/rafaelespinoza/homebrew-godfish

Drivers:
	cassandra, mysql, postgres, sqlite3, sqlserver"

	printf '%s\n' "${_usage_message}"
}

main() {
	case "${1}" in
	cassandra | mysql | postgres | sqlite3 | sqlserver)
		# keep going
		;;
	"" | "-h" | "--help" | "help" | "-help")
		usage >&2
		return 0
		;;
	*)
		usage >&2
		return 1
		;;
	esac

	driver=$1
	shift
	_binary_basename="godfish-${driver}"

	# This value may be replaced with a hardcoded value when doing `brew install`.
	LIBEXEC_DIR=''

	if [ -n "${LIBEXEC_DIR}" ]; then
		# This was probably installed via homebrew.
		binary_name="${LIBEXEC_DIR}/${_binary_basename}"
	else
		# Try these other possible installation locations.
		script_dir="$(cd -P "$(dirname "${0}")" && pwd)"

		if [ -x "${script_dir}/${_binary_basename}" ]; then
			# The driver binary lives in the same directory as this script.
			binary_name="${script_dir}/${_binary_basename}"
		elif [ -x "${script_dir}/../libexec/${_binary_basename}" ]; then
			# Local non-Homebrew layout that mimics a structure where binaries are in libexec.
			binary_name="${script_dir}/../libexec/${_binary_basename}"
		elif command -v "${_binary_basename}" >/dev/null 2>&1; then
			# The driver binary is available in the user's global $PATH.
			binary_name=$(command -v "${_binary_basename}")
		elif command -v brew >/dev/null 2>&1 && [ -x "$(brew --prefix godfish 2>/dev/null)/libexec/${_binary_basename}" ]; then
			# Fall back to Homebrew lookup if brew exists but the libexec value wasn't replaced upon brew install.
			binary_name="$(brew --prefix godfish)/libexec/${_binary_basename}"
		else
			printf "ERROR: unknown or uninstalled driver '%s'\n" "${driver}" >&2
			return 1
		fi
	fi

	if [ ! -x "${binary_name}" ]; then
		printf "ERROR: driver binary found at '%s' but is not executable\n" "${binary_name}" >&2
		return 1
	fi

	exec "${binary_name}" "${@}"
}

main "${@}"
