services:
    client:
        build:
            context: ../..
            dockerfile: .ci/mysql/client.Containerfile
        depends_on:
            - server
        entrypoint: /client.sh server
        env_file: env
        environment:
            CGO_ENABLED: 0
            # Seems like existing env vars can't be used to create new env vars.
            # The schema for a connection string is roughly:
            #   "$db_user:$db_password@tcp($db_host)/$db_name"
            DB_DSN: "godfish:password@tcp(server)/godfish_test"
        tty: true
        volumes:
            -
                type: bind
                source: /tmp/godfish_test/mariadb/.test_coverage
                target: /tmp
    server:
        image: docker.io/mariadb:10.6
        env_file: env
        expose:
            - 3306
        volumes:
            -
                type: volume
                source: server
                target: /var/lib/mysql

volumes:
    server:
