version: "3.9"

services:
    client:
        build:
            context: "${BUILD_DIR}"
            dockerfile: "${BUILD_DIR}/.ci/mysql/client.Dockerfile"
        image: godfish_test/mysql/client:latest
        container_name: godfish_ci_mysql_client
        depends_on:
          - server
        entrypoint: /client.sh server
        env_file: env
        environment:
            CGO_ENABLED: 0
            # Seems like existing env vars can't be used to create new env vars.
            # The schema for a connection string is roughly:
            #   "$db_user:$db_password@tcp($db_host)/$db_name"
            DB_DSN: "godfish:password@tcp(server)/godfish_test"
        tty: true
    server:
        build:
            context: "${BUILD_DIR}"
            dockerfile: "${BUILD_DIR}/.ci/mysql/mysql_server_v57.Dockerfile"
        image: godfish_test/mysql/server_v57:latest
        container_name: godfish_ci_mysql_server_v57
        env_file: env
        expose:
            - 3306
        volumes:
            -
              type: volume
              source: server
              target: /var/lib/mysql

volumes:
    server:
