name: postgres
on: [push, pull_request]
jobs:
  v15:
    name: postgres v15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Build environment and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just -f ci.Justfile postgres15-up
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        env:
          DATADIR: .ci/.test_coverage/postgres_v15
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ${{ env.DATADIR }}/cover.out,${{ env.DATADIR }}/integration.out,${{ env.DATADIR }}/cover_driver.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Teardown
        run: just -f ci.Justfile postgres15-down
  v16:
    name: postgres v16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install just
        uses: extractions/setup-just@v3
      - name: Build environment and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just -f ci.Justfile postgres16-up
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        env:
          DATADIR: .ci/.test_coverage/postgres_v16
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ${{ env.DATADIR }}/cover.out,${{ env.DATADIR }}/integration.out,${{ env.DATADIR }}/cover_driver.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Teardown
        run: just -f ci.Justfile postgres16-down
