---
name: install
on:
  push:
    paths: [.github/scripts/setup_install_test.sh, .github/scripts/test_install.sh, .github/workflows/install.yaml, scripts/install.sh]
  pull_request:
    paths: [.github/scripts/setup_install_test.sh, .github/scripts/test_install.sh, .github/workflows/install.yaml, scripts/install.sh]
  release:
    types: [created, released]
  workflow_dispatch:
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck .github/scripts/*.sh ./scripts/install.sh

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions: { contents: read }
    env:
      LOG_LEVEL: 3
      BASE_INSTALL_DIR: /tmp/bin
      IS_LINUX: ${{ contains(matrix.os, 'ubuntu') }}
      IS_MACOS: ${{ contains(matrix.os, 'macos') }}
      TERM: xterm # so that bats can pretty-print error messages.
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Bats and bats libs
        id: setup-bats
        with:
          support-path: "${{ github.workspace }}/.github/bats/bats-support"
          assert-path: "${{ github.workspace }}/.github/bats/bats-assert"
          file-path: "${{ github.workspace }}/.github/bats/tests/bats-file"
          github-token: ${{ secrets.GITHUB_TOKEN }}
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0

      - name: Test using gh
        timeout-minutes: 5
        env:
          WANT_GH: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_INSTALL_DIR: ${{ env.BASE_INSTALL_DIR }}/want_gh
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          echo >&2 "# running setup_install_test.sh"
          .github/scripts/setup_install_test.sh

          echo >&2 "# testing install.sh"
          bats --abort --pretty --print-output-on-failure .github/scripts/test_install.sh

      - name: Test w/o gh; use curl for downloads; use jq to parse responses
        timeout-minutes: 5
        env:
          WANT_GH: false
          WANT_CURL: true
          WANT_JQ: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_INSTALL_DIR: ${{ env.BASE_INSTALL_DIR }}/no_gh_use_curl
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          echo >&2 "# running setup_install_test.sh"
          .github/scripts/setup_install_test.sh

          echo >&2 "# testing install.sh"
          bats --abort --pretty --print-output-on-failure .github/scripts/test_install.sh

      - name: Test w/o gh or curl; use wget for downloads; use jq to parse responses
        timeout-minutes: 5
        env:
          WANT_GH: false
          WANT_CURL: false
          WANT_JQ: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_INSTALL_DIR: ${{ env.BASE_INSTALL_DIR }}/no_gh_use_wget
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          echo >&2 "# running setup_install_test.sh"
          .github/scripts/setup_install_test.sh

          echo >&2 "# testing install.sh"
          bats --abort --pretty --print-output-on-failure .github/scripts/test_install.sh

      - name: Test w/o gh or jq; use curl for downloads; use a pipeline to parse responses
        timeout-minutes: 5
        env:
          WANT_GH: false
          WANT_CURL: true
          WANT_JQ: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_INSTALL_DIR: ${{ env.BASE_INSTALL_DIR }}/no_gh_use_curl_no_jq
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          echo >&2 "# running setup_install_test.sh"
          .github/scripts/setup_install_test.sh

          echo >&2 "# testing install.sh"
          bats --abort --pretty --print-output-on-failure .github/scripts/test_install.sh

      - name: Test w/o gh, curl or jq; use wget for downloads; use a pipeline to parse responses
        timeout-minutes: 5
        env:
          WANT_GH: false
          WANT_CURL: false
          WANT_JQ: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_INSTALL_DIR: ${{ env.BASE_INSTALL_DIR }}/no_gh_use_wget_no_jq
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: |
          echo >&2 "# running setup_install_test.sh"
          .github/scripts/setup_install_test.sh

          echo >&2 "# testing install.sh"
          bats --abort --pretty --print-output-on-failure .github/scripts/test_install.sh
