name: mysql
on: [push, pull_request]
jobs:
  mariadb:
    name: mariadb v10.6
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build environment and run tests
      run: make -f ci.Makefile ci-mariadb-up
    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: /tmp/cover.out,/tmp/cover_driver.out
        verbose: true
    - name: Teardown
      run: make -f ci.Makefile ci-mariadb-down
  mysql_v57:
    name: mysql v5.7
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build environment and run tests
      run: make -f ci.Makefile ci-mysql57-up
    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: /tmp/cover.out,/tmp/cover_driver.out
        verbose: true
    - name: Teardown
      run: make -f ci.Makefile ci-mysql57-down
  mysql_v8:
    name: mysql v8.0
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build environment and run tests
      run: make -f ci.Makefile ci-mysql8-up
    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: /tmp/cover.out,/tmp/cover_driver.out
        verbose: true
    - name: Teardown
      run: make -f ci.Makefile ci-mysql8-down
  security_scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run gosec
      uses: securego/gosec@master
      with:
        args: . ./internal/... ./drivers/mysql/...
