FROM godfish_test/client_base:latest

WORKDIR /src
RUN apk update && \
  apk --no-cache add musl-dev sqlite && \
  just build-sqlite3 && \
  just build-sqlite3-test

COPY .ci/sqlite3/client.sh /
ENTRYPOINT /client.sh
